### ISSUE TITLE
Unable to upload documents

### ISSUE THREAD

**Issue by mimmus** [open-webui/helm-charts#128]
Hi,
I'm currently running openweb-ui under Kubernetes, using this chart, with persistency enabled, and getting these errors during upload of a small document under a Knowledge collection:
```
INFO  [open_webui.apps.retrieval.main] adding to collection file-360135f9-ea48-4664-bd77-b702719f084e
HTTPConnectionPool(host='host.docker.internal', port=11434): Max retries exceeded with url: /api/embed (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f1774bb18d0>: Failed to resolve 'host.docker.internal' ([Errno -2] Name or service not known)"))
ERROR [open_webui.apps.retrieval.main] 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/app/backend/open_webui/apps/retrieval/main.py", line 854, in save_docs_to_vector_db
    embeddings = embedding_function(
                 ^^^^^^^^^^^^^^^^^^^
  File "/app/backend/open_webui/apps/retrieval/utils.py", line 267, in <lambda>
    return lambda query: generate_multiple(query, func)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/backend/open_webui/apps/retrieval/utils.py", line 262, in generate_multiple
    embeddings.extend(func(query[i : i + embedding_batch_size]))
TypeError: 'NoneType' object is not iterable
ERROR [open_webui.apps.retrieval.main] 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/app/backend/open_webui/apps/retrieval/main.py", line 1028, in process_file
    raise e
  File "/app/backend/open_webui/apps/retrieval/main.py", line 1002, in process_file
    result = save_docs_to_vector_db(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/backend/open_webui/apps/retrieval/main.py", line 876, in save_docs_to_vector_db
    raise e
  File "/app/backend/open_webui/apps/retrieval/main.py", line 854, in save_docs_to_vector_db
    embeddings = embedding_function(
                 ^^^^^^^^^^^^^^^^^^^
  File "/app/backend/open_webui/apps/retrieval/utils.py", line 267, in <lambda>
    return lambda query: generate_multiple(query, func)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/backend/open_webui/apps/retrieval/utils.py", line 262, in generate_multiple
    embeddings.extend(func(query[i : i + embedding_batch_size]))
TypeError: 'NoneType' object is not iterable
ERROR [open_webui.apps.webui.routers.files] 400: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/app/backend/open_webui/apps/retrieval/main.py", line 1028, in process_file
    raise e
  File "/app/backend/open_webui/apps/retrieval/main.py", line 1002, in process_file
    result = save_docs_to_vector_db(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/backend/open_webui/apps/retrieval/main.py", line 876, in save_docs_to_vector_db
    raise e
  File "/app/backend/open_webui/apps/retrieval/main.py", line 854, in save_docs_to_vector_db
    embeddings = embedding_function(
                 ^^^^^^^^^^^^^^^^^^^
  File "/app/backend/open_webui/apps/retrieval/utils.py", line 267, in <lambda>
    return lambda query: generate_multiple(query, func)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/backend/open_webui/apps/retrieval/utils.py", line 262, in generate_multiple
    embeddings.extend(func(query[i : i + embedding_batch_size]))
TypeError: 'NoneType' object is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/backend/open_webui/apps/webui/routers/files.py", line 71, in upload_file
    process_file(ProcessFileForm(file_id=id))
  File "/app/backend/open_webui/apps/retrieval/main.py", line 1037, in process_file
    raise HTTPException(
fastapi.exceptions.HTTPException: 400: 'NoneType' object is not iterable
```

Obviously, `host.docker.internal` makes no sense under Kubernetes.
Is it a bug?

**Comment by mimmus** [comment]
Just noticed right setting under Admin Panel -> . Sorry
